### ISSUE TITLE
Primary triggers & periods 

### ISSUE THREAD

**Issue by YasuyukiOkumura** [UCATLAS/ZJetBalance#29]
Dear Gabriel and Brian, 

Here is a list of primary triggers :
https://twiki.cern.ch/twiki/bin/viewauth/Atlas/LowestUnprescaled

We need to remember this is for C2-C4, 
and if we use some early data, we need to take the special trigger configuration into account.
(e.g. L1 only or lower HLT)

I think it would be good to be simple so far.
We can just focus on C2-C4 data, and use the primary trigger summarized in the TWiki. 

How do you like this idea?

**Comment by btuan** [comment]
Yasu,

Thanks for the list -- this is useful! 

I just did a quick lumicalc on the HLT_mu20_iloose_L1MU15 trigger, and it appears we get around [78 pb^-1](https://atlas-lumicalc.cern.ch/results/d387a7/result.html) of prescale corrected data (period C2->C5) from that. 

For HLT_e24_lhmedium_L1EM18VH, we get [around 62 pb^-1](https://atlas-lumicalc.cern.ch/results/631205/result.html) data. 

I will try using these -- both are included in the [SUSY2 derivation](https://svnweb.cern.ch/trac/atlasoff/browser/PhysicsAnalysis/DerivationFramework/DerivationFrameworkSUSY/trunk/share/SUSY2.py), so that's good!

Brian
