### ISSUE TITLE
eta dependence

### ISSUE THREAD

**Issue by gfacini** [UCATLAS/ZJetBalance#45]
balance in bins of eta - was this done in the Run I version?

|detector eta| < 0.8
0.8 < |detector eta| < 1.6
1.6 < |detector eta| < 2.5

**Comment by YasuyukiOkumura** [comment]
It's implemented! I will report it in different thread.

**Comment by YasuyukiOkumura** [comment]
I will reopen this ticket. since I found that I wrongly used constituent scale eta for the previous plots, 
and jet EM scale Eta was not filled properly so far 
(apparently due to the configuration in derivation stage),

Gabriel, please remember that the currently plots are binned with calibrated eta! 

Best regards,
Yasu Okumura
